### ISSUE TITLE
Too much whitespace in the hero

### ISSUE THREAD

**Issue by krishguptadev** [avneesh0612/portfolio-template#6]
Perhaps center the hero: 
![image](https://user-images.githubusercontent.com/91655303/143448052-670e98a3-ed28-4841-a7b5-788fb72653c5.png)

**Comment by avneesh0612** [comment]
Do you mean the space on right or bottom?

**Comment by krishguptadev** [comment]
> Do you mean the space on right or bottom?

bottom

**Comment by avneesh0612** [comment]
Oh okay. I will try to see what I can do 🤔

**Comment by avneesh0612** [comment]
Hey, I think this issue is foxed now
